"""Download public transaction context and calibration priors for BankVerse.

Public datasets provide transaction envelopes and fraud-distribution context only.
They do not provide provider-routing labels. Provider outcomes are generated by
scripts/generate-hybrid-dataset.ts.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import pandas as pd
from datasets import load_dataset

ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = ROOT / "data"
PUBLIC_DATASET = "techaudit/Dante-Synthetic-AML-Finance-V1"
IEEE_DATASET = "alexkstern/full_european_credit_card_fraud_dataset"
DANTE_DATASET = "techaudit/Dante-Synthetic-AML-Finance-V1"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--envelope-dataset", default=PUBLIC_DATASET)
    parser.add_argument("--ieee-dataset", default=IEEE_DATASET)
    parser.add_argument("--dante-dataset", default=DANTE_DATASET)
    parser.add_argument("--envelope-limit", type=int, default=50_000)
    parser.add_argument("--ieee-limit", type=int, default=200_000)
    parser.add_argument("--dante-limit", type=int, default=30_000)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--skip-dante", action="store_true")
    return parser.parse_args()


def load_frame(dataset_name: str, limit: int, seed: int) -> pd.DataFrame:
    dataset = load_dataset(dataset_name, split="train")
    frame = dataset.to_pandas()
    if frame.empty:
        raise ValueError(f"Dataset {dataset_name} returned no rows")
    sample_size = min(limit, len(frame))
    return frame.sample(n=sample_size, random_state=seed).reset_index(drop=True)


def find_column(frame: pd.DataFrame, candidates: list[str]) -> str | None:
    normalized = {str(column).strip().lower().replace(" ", "_"): str(column) for column in frame.columns}
    for candidate in candidates:
        if candidate in normalized:
            return normalized[candidate]
    return None


def clean_envelopes(frame: pd.DataFrame, source: str) -> pd.DataFrame:
    amount_column = find_column(frame, ["amount", "transaction_amount", "transaction_value", "transactionamt"])
    timestamp_column = find_column(frame, ["timestamp", "date", "transaction_date", "time", "transactiondt"])
    category_column = find_column(frame, ["category", "merchant_category", "merchant", "classification"])
    method_column = find_column(frame, ["payment_method", "card_type", "method", "type"])

    if not amount_column or not timestamp_column:
        raise ValueError(
            f"{source} must contain amount and timestamp-like columns; "
            f"found columns: {list(frame.columns)[:20]}"
        )

    timestamp = pd.to_datetime(frame[timestamp_column], errors="coerce", utc=True)
    if timestamp.isna().all():
        raise ValueError(f"{source} has no parseable timestamps in {timestamp_column}")

    amounts = pd.to_numeric(
        frame[amount_column].astype(str).str.replace(r"[^0-9.-]", "", regex=True),
        errors="coerce",
    )
    valid = amounts.notna() & amounts.gt(0) & timestamp.notna()
    cleaned = pd.DataFrame(
        {
            "transaction_id": [f"{source.replace('/', '_')}_{index}_public" for index in frame.index],
            "amount": amounts.abs().round(2),
            "timestamp": timestamp,
            "merchant_category": frame[category_column].fillna("unknown") if category_column else "unknown",
            "payment_method": frame[method_column].fillna("card") if method_column else "card",
            "source": f"public_{source.replace('/', '_')}",
        }
    )
    cleaned = cleaned.loc[valid].copy()
    cleaned["hour"] = cleaned["timestamp"].dt.hour
    cleaned["day_of_week"] = cleaned["timestamp"].dt.dayofweek
    cleaned["public_source_id"] = cleaned["transaction_id"]
    return cleaned.reset_index(drop=True)


def build_ieee_priors(frame: pd.DataFrame) -> pd.DataFrame:
    amount_column = find_column(frame, ["transactionamt", "amount", "transaction_amount"])
    fraud_column = find_column(frame, ["isfraud", "is_fraud", "fraud", "class"])
    time_column = find_column(frame, ["transactiondt", "timestamp", "time"])
    if not amount_column or not fraud_column or not time_column:
        raise ValueError("IEEE dataset must contain TransactionAmt, isFraud, and TransactionDT-like columns")

    amounts = pd.to_numeric(frame[amount_column], errors="coerce")
    fraud = pd.to_numeric(frame[fraud_column], errors="coerce")
    if str(frame[time_column].dtype).startswith("datetime"):
        timestamp = pd.to_datetime(frame[time_column], errors="coerce", utc=True)
    else:
        numeric_time = pd.to_numeric(frame[time_column], errors="coerce")
        timestamp = pd.to_datetime(numeric_time, unit="s", origin="2020-01-01", utc=True)
    prepared = pd.DataFrame({"amount": amounts, "is_fraud": fraud, "timestamp": timestamp}).dropna()
    prepared = prepared[prepared["amount"] > 0]
    prepared["amount_bucket"] = pd.cut(
        prepared["amount"],
        bins=[0, 10, 50, 100, 500, 10_000, float("inf")],
        labels=["0-10", "10-50", "50-100", "100-500", "500-10000", "10000+"],
        include_lowest=True,
    )
    prepared["hour"] = prepared["timestamp"].dt.hour
    priors = (
        prepared.groupby(["amount_bucket", "hour"], observed=False)
        .agg(
            fraud_proxy_rate=("is_fraud", "mean"),
            transaction_count=("is_fraud", "count"),
        )
        .reset_index()
    )
    priors["amount_bucket"] = priors["amount_bucket"].astype(str)
    return priors


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def write_manifest(manifest: dict[str, Any]) -> None:
    manifest_path = DATA_DIR / "public_manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")


def main() -> None:
    args = parse_args()
    DATA_DIR.mkdir(parents=True, exist_ok=True)

    envelope_frame = clean_envelopes(
        load_frame(args.envelope_dataset, args.envelope_limit, args.seed),
        args.envelope_dataset,
    )
    if not args.skip_dante:
        try:
            dante = clean_envelopes(
                load_frame(args.dante_dataset, args.dante_limit, args.seed),
                args.dante_dataset,
            )
            envelope_frame = pd.concat([envelope_frame, dante], ignore_index=True)
            dante_status = {"status": "loaded", "rows": len(dante)}
        except Exception as error:  # Optional fallback must not block the primary dataset.
            dante_status = {"status": "skipped", "reason": str(error)}
    else:
        dante_status = {"status": "disabled"}

    ieee_frame = load_frame(args.ieee_dataset, args.ieee_limit, args.seed)
    priors = build_ieee_priors(ieee_frame)

    envelope_path = DATA_DIR / "public_envelopes.csv"
    priors_path = DATA_DIR / "failure_priors.json"
    envelope_frame.to_csv(envelope_path, index=False)
    priors.to_json(priors_path, orient="records", indent=2)

    manifest = {
        "version": "public-ingestion.v1",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "seed": args.seed,
        "envelopes": {
            "dataset": args.envelope_dataset,
            "rows": len(envelope_frame),
            "sha256": sha256_file(envelope_path),
            "output": str(envelope_path.relative_to(ROOT)),
        },
        "failure_priors": {
            "dataset": args.ieee_dataset,
            "rows": len(priors),
            "sha256": sha256_file(priors_path),
            "output": str(priors_path.relative_to(ROOT)),
            "label_semantics": "fraud_proxy_rate; not a provider decline label",
        },
        "dante": dante_status,
    }
    write_manifest(manifest)
    print(json.dumps(manifest, indent=2))


if __name__ == "__main__":
    main()
